server:
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///instancepostgresql1
    username: shauna
    password: 1111
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: instancepostgresql1:us-central1:instancepostgresql1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect