spring.application.name=Url_shortener

!spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/url_shortener
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener 
!spring.datasource.url=jdbc:postgresql://db:5432/url_shortener
spring.datasource.username=shauna
spring.datasource.password=1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public


url.shortener.base-url=shauna.com/

#logging.level.root=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=DEBUG



